#!/usr/bin/env bash
# ./miri run playground/simple.rs > playground/simple.log
# ./miri run playground/rc_as_pinmut.rs > playground/rc_as_pinmut.log
./miri run playground/closure_capture.rs > playground/closure_capture.log
